### ISSUE TITLE
Make it like ruby

### ISSUE THREAD

**Issue by darrencauthon** [bararchy/safe-t-rest#1]
Hi, I saw your question asking for input on your first gem...

My first thought after looking at the code is that it's not very ruby-ish.  You are not following many basic ruby conventions, like two-spaces over tabs, snake_case, basic tests, a Rakefile, etc.  

Many of these practices can be found here:  https://github.com/styleguide/ruby

I know, there are many opinions on style.  Who is to say one is better than the other??? ... I get that, but this isn't quibbling over semicolons.  This gem's code looks like it was written by a Java or C# dev.

**Comment by bararchy** [comment]
Ok, 
Thanks so much for taking the time and look at the code, I have made changes to the 'lib', would you care to re-review them ? 

Also down from 1 file inspected, 67 offenses detected
to 1 file inspected, 14 offenses detected
Using rubucop, so I guess I did some good :)

**Comment by darrencauthon** [comment]
That looks a lot better!  I'll have some other suggestions coming in a bit.
