### ISSUE TITLE
A lot of duplication in the code

### ISSUE THREAD

**Issue by recursive-madman** [bararchy/safe-t-rest#3]
Namely, all the public methods have this in common:
- they call send_request
- they pass Username:'', Password:'', RoleID: '#{@role_id}', ExtensionID: '#{@extension_id}'
- they pass their an action name and arguments
  The first two can easily be done in a single place.

Then the public methods could reduce to something like:

``` ruby
def get_package_file_list(guid)
  call_remote('GetPackageFileList', guid)
end
```

where `call` would build the request string out of it's arguments and the defaults (Username, Password, ...).

**Comment by bararchy** [comment]
Good idea: 83f872b6b1d1389cd41df8765c6720895701148e

Is that better ?
